### ISSUE TITLE
No Article at first

### ISSUE THREAD

**Issue by christophkormesser** [mihairinzis/MMM-wiki#3]
Hi, I have the issue, that when I start the mirror no article is shown (it says "no articles fetched"). The first one is shown after my custom interval (10 minutes (600.000ms)), but it would be nice if the first article is shown right after bootup. Sadly I have no experience in JavaScript and can't fix it myself right now.
- and btw, can I change the size (pixels) of the letters used in the articles?

Thank you for this module, well done! :)

**Comment by pooyasa** [comment]
Hey,
I dunno about the no article fetched but to make the font smaller, you can add these two lines of code at line 115 of MMM-wiki.js after "wrapper.innerHTML = article.content;":
`		    wrapper.classList.add("small");
		    wrapper.classList.add("light");`

**Comment by mihairinzis** [comment]
should be fixed with https://github.com/mihairinzis/MMM-wiki/commit/075a5e9f8dce019d3c1e174e8ca6e0dec61b6f54
